version: "3.8"

services:
  bot:
    build: .
    restart: always
    volumes:
      - .:/app
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS}
    command: python bot.py
